server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://fraud-db:5432/frauddb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/paytrack/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: fraud-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.paytrack.shared.dto"

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

  instance:
    hostname: fraud-service
    prefer-ip-address: false