server:
  port: 8085

spring:
  application:
    name: paytrack-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: account-service
          uri: lb://payment-service
          predicates:
            - Path=/api/accounts/**

        - id: card-service
          uri: lb://payment-service
          predicates:
            - Path=/api/cards/**

        - id: payment-config-service
          uri: lb://payment-service
          predicates:
            - Path=/api/configs/**

        - id: fraud-service
          uri: lb://fraud-service
          predicates:
            - Path=/api/fraud/**

        - id: payment-api-docs
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/v3/api-docs/**,/payment-service/v3/api-docs
          filters:
            - RewritePath=/payment-service/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

        - id: payment-swagger-ui
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/swagger-ui/**
          filters:
            - RewritePath=/payment-service/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: payment-service
        url: /payment-service/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG